"""empty message

Revision ID: 229f0fc2c0f4
Revises: 7094f6e16fa5
Create Date: 2019-03-30 23:30:57.584103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229f0fc2c0f4'
down_revision = '7094f6e16fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'number')
    # ### end Alembic commands ###
