"""empty message

Revision ID: 355fe247b0e2
Revises: 
Create Date: 2019-03-23 21:38:17.413840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355fe247b0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concerts_name'), 'concerts', ['name'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('application', sa.DATETIME(), nullable=True),
    sa.Column('winning', sa.DATETIME(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_concert_id'), 'tickets', ['concert_id'], unique=False)
    op.create_index(op.f('ix_tickets_member_id'), 'tickets', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_member_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_concert_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_concerts_name'), table_name='concerts')
    op.drop_table('concerts')
    # ### end Alembic commands ###
