"""empty message

Revision ID: 5ea335a2f9d6
Revises: c519f3f4c1d2
Create Date: 2019-03-26 16:44:42.958914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ea335a2f9d6'
down_revision = 'c519f3f4c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_members_name', table_name='members')
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.create_index('ix_members_name', 'members', ['name'], unique=True)
    op.alter_column('members', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
